port: 8080

mysql:
  uri: "root:123456@tcp(mysql-example:3306)/photogramm"
  # uri: "root:123456@/photogramm"

default_album_name: "default album"

jwtKey: "8dasdiadi9329i3kd9d"

local_storage: "./storage"

mongo:
uri: "mongodb://mongo:123456@mongo-example:27017/?maxPoolSize=20&w=majority"
